// zeno/src/App.tsx
import { BrowserRouter as Router } from 'react-router-dom';
import Navbar from './components/layout/Navbar';
import Hero from './components/sections/Hero';
import Services from './components/sections/Services';

function App() {
  return (
    <Router>
      <div className="min-h-screen bg-primary">
        <Navbar />
        <main>
          <Hero />
          <Services />
        </main>
      </div>
    </Router>
  );
}

export default App

// my-vue-app/src/App.vue
<template>
	<div class="min-h-screen bg-gray-50">
	  <TheNavbar />
	  <main>
		<HeroSection />
		<ServicesSection />
		<AboutSection />
		<ContactSection />
	  </main>
	  <TheFooter />
	</div>
  </template>
  
  <script>
  import TheNavbar from './components/layout/TheNavbar.vue'
  import TheFooter from './components/layout/TheFooter.vue'
  import HeroSection from './components/sections/HeroSection.vue'
  import ServicesSection from './components/sections/ServicesSection.vue'
  import AboutSection from './components/sections/AboutSection.vue'
  import ContactSection from './components/sections/ContactSection.vue'
  
  export default {
	name: 'App',
	components: {
	  TheNavbar,
	  TheFooter,
	  HeroSection,
	  ServicesSection,
	  AboutSection,
	  ContactSection
	}
  }
  </script>
